try{
    console.log(naoExisto);
}catch(e){
    console.log(e);
}